chapter02/TenArmedTestbed.py
Use the [violinplot](http://seaborn.pydata.org/generated/seaborn.violinplot.html?highlight=violin#seaborn.violinplot) function in [Seaborn](http://seaborn.pydata.org/index.html) to plot figure 2.1
=> add Figure 2.1

chapter02/TenArmedTestbed.py
I guess there was a typo, when the $\alpha$ parameter value was left to $0.1$ instead of setting it to the variable.
=> Fix for the step size value for the non-average and non-gradient case.

chapter05/Blackjack.py
The fix should make the code run by roughly 10%.
=> Performance improvement.

chapter01/TicTacToe.py, chapter02/TenArmedTestbed.py, chapter03/GridWorld.py, chapter04/CarRental.py, chapter04/GamblersProblem.py, chapter04/GridWorld.py, chapter05/Blackjack.py, chapter05/InfiniteVariance.py, chapter06/CliffWalking.py, chapter06/MaximizationBias.py, chapter06/RandomWalk.py, chapter06/WindyGridWorld.py, chapter07/RandomWalk.py, chapter08/VariousMaze.py, chapter09/RandomWalk.py, chapter09/SquareWave.py, chapter10/AccessControl.py, chapter10/MountainCar.py, chapter11/Baird.py, chapter12/RandomWalk.py, extra/QSigma.py, extra/ReturnSpecificImportanceSampling.py, extra/SumOfTDErrors.py, utils/TileCoding.py, utils/__init__.py
The followings are not yet completed.
- chap2.
- chap10.
If the fix is welcomed to the project, I'll modify the above too. It seems not to be straight like others.
=> Modified the codes so that they have python v3 compatibility.

utils/utils.py
The fix got almost 2 times faster than current one without loosing the feature of "unique" option.
If we can use elements.max() instead of np.max(elemements), that would get the function much faster.
http://stackoverflow.com/questions/10943088/numpy-max-or-max-which-one-is-faster
=> Improved the performance of argmax.

chapter06/RandomWalk.py
according to `if not batch:` current states value, will be updated if @batch is False
=> update states when batch is False

chapter01/TicTacToe.py, chapter02/TenArmedTestbed.py, chapter03/GridWorld.py, chapter04/GamblersProblem.py, chapter04/GridWorld.py, chapter05/InfiniteVariance.py, chapter06/CliffWalking.py, chapter06/MaximizationBias.py, chapter06/RandomWalk.py, chapter06/WindyGridWorld.py, chapter07/RandomWalk.py, chapter08/VariousMaze.py, chapter09/RandomWalk.py, chapter09/SquareWave.py, chapter10/AccessControl.py, chapter10/MountainCar.py, chapter11/Baird.py, chapter12/RandomWalk.py, extra/QSigma.py, extra/ReturnSpecificImportanceSampling.py, extra/SumOfTDErrors.py, utils/__init__.py
Updated contribution list for python v3 compatibility.
=> Updated contribution list.

chapter05/Blackjack.py
This saves the np.where check, hopefully. Hopefully it also gives the same results. I checked both versions optically, and everything seems to be the same. However, I don't quite know how to test this code, given the random numbers. Perhaps adding a seed to the random number generator, but I am not convinced that this will help. 
I also added a few doc lines that would have made reading the code slightly simpler, at least for me.
=> divide by one

chapter06/RandomWalk.py
By using "enumerate", it's possible to have the same value in both
arrays.
=> Fix not allowing same value in both arrays

chapter06/RandomWalk.py, chapter06/WindyGridWorld.py
1. It's unclear if the graph is shown in black and white without using linestyle.
2. Add more messages so that it's easier to understand the output.
=> Make graph and messages more friendly

chapter06/WindyGridWorld.py
episodeLimit is set to be 500 later
=> Remove commented code

chapter03/GridWorld.py
The display for value functions in chapter03 is simply a numpy array. Why not pyplot table?
=> Changed the numpy array display of 'Random Policy' and 'Optimal Policy' to pyplot table

chapter13/ShortCorridor.py
Hi @ShangtongZhang ,
I'd like to contribute the code to reproduce the plot of example 13.1. Here is how it looks on my machine:
Please let me know if anything is missing.
Thank you,
Sergii
=> add example 13.1

chapter04/GridWorld.py, chapter04/GridWorldInPlaceVersion.py
I just add the 'in place' version in GridWorld of chapter 4, and compare the iteration times of convergence of two version.
=> Add in place version of  Chapter 4

chapter13/ReinforceShortCorridor.py
Hi @ShangtongZhang ,
This is a code to reproduce Figure 13.1 in the book. 
The learning rates that the book suggests are so tiny that they didn't work for me. I wonder if there is a typo, or I am missing something. But with the learning rate 2e-4 it can reach optimal value -11.8, and the probability of 'going right' approaches the theoretical 0.58.
=> Chapter 13, REINFORCE

chapter04/car_rental_backup_value.py
Policy evaluation with backed up value function with parallel implementation.
=> Policy evaluation with backed up value function.

chapter01/tic_tac_toe.py
1.Added self.symbol  in  Player. self.symbol was used without defined in method set_symbol() of class Player
2. Remove unnecessary parenthesis in return method act of class HumanPlayer.
3. Variable 'sum' is rename is 'sum_values' because 'sum' conflicted name keywords python and numpy.
4. Variables newSate, newHas, and isEnd are renamed as new_state new_hash, and is_end respectively for constancy and python code style.
=> Fixed few minor issues in chapter 1 tic_tac_toe:

.gitignore, chapter01/tic_tac_toe.py
1. use ``np.nditer`` to iterator over a numpy array
2. do not change state list to hash lists when calling ``backup()``
3. use const BOARD_SIZE
4. change ``dict.keys()`` to ``dict`` for checking keys existence
=> pythonic for chap01

chapter02/ten_armed_testbed.py
I think using `np.where()` is a tiny bit more intuitive and concise there :)
=> Choosing the best action when identical

chapter07/random_walk.py, chapter08/maze.py, chapter12/random_walk.py
Replaced `zip(range(len(..)), ..)` with `enumerate(..)` in three scripts.
Hope this helps.
Thanks!
=> Pythonic edits

chapter03/grid_world.py
Here I compute the values using the linear system of equations as mentioned in the book
=> Add linear system to gridworld

chapter03/grid_world.py
I added a function that allows to draw the arrows for the optimal policy computed from the optimal values (fig 3.5). It looks like this:
=> Add code to draw optimal policy

chapter03/grid_world.py
I made small modification to add state labels on the tables for improved visibility.
=> add state labels on the tables
